# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yyqapm/specs.git'

target 'SCClassRoom' do
pod 'thunder/thunderboltdynamic', '2.8.1'
pod 'Hummer', '3.1.5'

pod 'AFNetworking',                 '~> 3.2.1'
pod 'Masonry',                      '~> 1.1'
pod 'IQKeyboardManager',            '6.4.0'
pod 'MJExtension'
pod 'Whiteboard',                 '2.7.13'
pod 'MBProgressHUD',              '1.2.0'
end
